local L = AceLibrary("AceLocale-2.2"):new("MrPlow")

L:RegisterTranslations("enUS", function() return {
	["Mr Plow"] = true,
	["MrPlow"] = true,
	["That name again, is Mr Plow! A inventory/bank restacker/defragger. Append 'bank' to the commands while the bank window is open to apply them to your bank contents."] = true,
	["Mr Plow looks at your neat bags and shakes his head."] = true,
	["AceConsole-commands"] = { "/mp", "/mrplow", "/plow" },

	["Your bags rumble as Mr Plow gets busy and drives into your bags..."] = true,
	["There is a tinkle of broken glass and a soft \"D'oh!\""] = true,
	["It looks like two wet cats in a bag..."] = true,
	["You hear the theme music being hummed out of key."] = true,
	["The engine cuts off for a bit, followed by the sounds of an asthmatic cow and curses before spluttering on..."] = true,
	["You wince as something reverses into your lower back."] = true,
	["You hear a loud CRASH, and the ever present revolving noise of a single plate spinning on the ground."] = true,
	["The discordant noise of what sounds like a piano dropping onto a hessian sack full of lasagne fills your ears."] = true,
	["As he drives off into the sunset, your bags deflate somewhat due to the extra room now available. That name again, is Mr Plow!"	] = true,

	["Mr Plow does a three point turn and faces forward..."] = true,
	["Mr Plow changes gear into reverse..."] = true,
	["Mr Plow is facing"] = true,
	["forward."] = true,
	["backward."] = true,

	["You feel a great disturbance in the Force, as if millions of voices suddenly cried out in terror and were suddenly silenced..."] = true,
	["Oh wait. No. Just one."] = true,
	["There is a grumbling as the gag is removed."] = true,

	["Mr Plow will stack items from your bag to your bank by "] = true,
	["filling up current stacks"] = true,
	["filling up the bag that contains the same item"] = true,
	["filling up any other free space"] = true,
	[" and then "] = true,

	["Bank"] = true,
	["has been removed from the ignore list"] = true,
	["has been added to the ignore list"] = true,
	["Mr Plow has cleared the ignore list"] = true,
	["Mr Plow is ignoring:"] = true,
	["and bags: "] = true,
	["and bank bags: "] = true,

	["Stack"] = true,
	["Plow"] = true,
	["Sort"] = true,
	["Bank Stack"] = true,
	["Sorts your inventory."] = true,
	["Sorts your bank."] = true,
	["The Works"] = true,
	["Stacks, plows and sorts. All in one."] = true,
	["Moves stuff from your bags to your bank."] = true,
	["Defragments your inventory."] = true,
	["Defragments your bank."] = true,
	["Bank Stack Style"] = true,
	["bankstackstyle"] = true,

	["Filter Junk"] = true,
	["filterjunk"] = true,
	["Moves all greys to the end."] = true,
	["Click To Run"] = true,
	["clicktorun"] = true,
	["Disables the click to run functionality."] = true,

	["Status"] = true,
	["Shows the current options set for Mr Plow."] = true,
	["Properties"] = true,
	["Mr Plow Properties"] = true,
	["Direction"] = true,
	["Change the plow direction."] = true,
	["Forwards"] = true, 
	["Backwards"] = true,
	["Gag"] = true,
	["Silence output"] = true,
	["Toggles the bank stack style."] = true,
	["ignore"] = true,
	["Bank commands"] = true,
	["Compresses your inventory."] = true,
	["Compresses your bank."] = true,
	["Modifies your ignore list."] = true,
	["add"] = true,
	["add item(s) to the ignore list, just shiftclick."] = true,
	["del"] = true,
	["remove item(s) from the ignore list, just shiftclick."] = true,
	
	["clear"] = true,
	["clear the ignore list completely."] = true,
	
	["bag"] = true,
	["ignore specific bags."] = true,
	
	["add a bag to the ignore list. Use '0' for the backpack, and 1-4 for the others. Use a single number or a comma separated list."] = true,
	["remove bags from the ignore list. Use '0' for the backpack, and 1-4 for the others, Use a single number or a comma separated list."] = true,
	["clear the ignore bag list."] = true,
	["slot"] = true,
	["ignore specific slots."] = true,
	["add slots to the ignore list. Use '0' for the backpack, and 1-4 for the others in the form bag-slot (eg 1-12). Use a single entry or a comma separated list."] = true,
	["remove slots from the ignore list. Use '0' for the backpack, and 1-4 for the others in the form bag-slot (eg 1-12), Use a single entry or a comma separated list."] = true,
	["addmouse"] = true,
	["add slots to the ignore list. Place the cursor over the intended bagslot to ignore and run the command."] = true,
	["delmouse"] = true,
	["remove slots from the ignore list. Place the cursor over the intended bagslot to unignore and run the command."] = true,
	["clear the ignore slot list."] = true,
	["bankbag"] = true,
	["ignore specific bankbags."] = true,
	["add a bankbag to the ignore list. Use '0' for the main bank window, and 1-6 for the others. Use a single number or a comma separated list."] = true,
	["remove bags from the ignore list. Use '0' for the main bank window, and 1-6 for the others, Use a single number or a comma separated list."] = true,
	["clear the ignore bankbag list."] = true,
	["|cffeda55fClick|r to run The Works on your bag, |cffeda55fShift-Click|r to run Bank The Works, |cffeda55fShift-Control-Click|r to run BankStack. |cffeda55fClick|r again to cancel."] = true,
	["|cffeda55fRight-Click|r for options."] = true,
	["Stopping"] = true,
--
-- Localisers, the following need to be -precisely- what your client calls them. This organises the sorting order.
	["Armor"] = true,
	["Weapon"] = true,
	["Quest"] = true,
	["Key"] = true,
	["Recipe"] = true,
	["Reagent"] = true,
	["Consumable"] = true,
	["Container"] = true,
	["Quiver"] = true,
	["Miscellaneous"] = true,
	["Projectile"] = true,
	["Trade Goods"] = true,
} end )
